#!/usr/bin/env bash
# Self-contained restore script generated by mac-backup.
# Run on a fresh Mac after copying these 4 files anywhere:
#   {{TS}}.tar.enc
#   {{TS}}.config.json
#   {{TS}}.log
#   uncrypt-and-restore-{{TS}}.sh   <-- this file
#
# Usage:  bash uncrypt-and-restore-{{TS}}.sh

set -euo pipefail

TS="{{TS}}"
ENC_ALGO="{{ENC_ALGO}}"
ENC_KDF="{{ENC_KDF}}"
ENC_ITER="{{ENC_ITER}}"

cd "$(dirname "$0")"

ENC_FILE="${TS}.tar.enc"
CFG_FILE="${TS}.config.json"
LOG_FILE="${TS}.log"

red()    { printf "\033[31m%s\033[0m\n" "$*"; }
green()  { printf "\033[32m%s\033[0m\n" "$*"; }
yellow() { printf "\033[33m%s\033[0m\n" "$*"; }
blue()   { printf "\033[34m%s\033[0m\n" "$*"; }

step() { blue "==> $*"; }

# ---------- 1. Sanity ----------
step "Checking sibling files exist"
for f in "$ENC_FILE" "$CFG_FILE" "$LOG_FILE"; do
  [ -f "$f" ] || { red "Missing: $f"; exit 1; }
done
green "  All 3 sibling files present"

# ---------- 2. Decrypt ----------
step "Decrypting $ENC_FILE"
TMP=$(mktemp -d -t mac-backup-restore)
TAR_FILE="$TMP/${TS}.tar"
trap 'rm -rf "$TMP"' EXIT

openssl enc -d -"$ENC_ALGO" -"$ENC_KDF" -iter "$ENC_ITER" \
  -in "$ENC_FILE" -out "$TAR_FILE"
green "  Decrypted to $TAR_FILE"

# ---------- 3. Extract ----------
step "Extracting tarball"
EXTRACT_DIR="$TMP/extracted"
mkdir -p "$EXTRACT_DIR"
tar -xf "$TAR_FILE" -C "$EXTRACT_DIR"
green "  Extracted"

# ---------- 4. Homebrew + Brewfile ----------
if [ -f "$EXTRACT_DIR/Brewfile" ]; then
  step "Installing Homebrew (if missing)"
  if ! command -v brew >/dev/null; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
  eval "$(/opt/homebrew/bin/brew shellenv)"

  step "Running brew bundle"
  brew bundle install --file="$EXTRACT_DIR/Brewfile" || \
    yellow "  brew bundle had failures — review above and re-run if needed"
else
  yellow "No Brewfile in archive — skipping brew step"
fi

# ---------- 5. $HOME dotfiles ----------
if [ -d "$EXTRACT_DIR/home" ]; then
  step "Restoring \$HOME files"
  rsync -a "$EXTRACT_DIR/home/" "$HOME/"
  green "  rsynced into \$HOME"
fi

# ---------- 6. VS Code ----------
if [ -d "$EXTRACT_DIR/vscode" ]; then
  step "Restoring VS Code settings"
  VSC="$HOME/Library/Application Support/Code/User"
  mkdir -p "$VSC/snippets"
  for f in settings.json keybindings.json; do
    [ -f "$EXTRACT_DIR/vscode/$f" ] && cp "$EXTRACT_DIR/vscode/$f" "$VSC/$f"
  done
  [ -d "$EXTRACT_DIR/vscode/snippets" ] && \
    rsync -a "$EXTRACT_DIR/vscode/snippets/" "$VSC/snippets/"
  green "  Settings + snippets restored"

  if [ -f "$EXTRACT_DIR/vscode/extensions.txt" ]; then
    if command -v code >/dev/null; then
      step "Installing VS Code extensions"
      xargs -L1 code --install-extension < "$EXTRACT_DIR/vscode/extensions.txt" || true
    else
      yellow "  'code' CLI not on PATH. Install it from VS Code (Cmd+Shift+P -> 'Shell Command: Install code'), then:"
      yellow "    xargs -L1 code --install-extension < $EXTRACT_DIR/vscode/extensions.txt"
    fi
  fi
fi

# ---------- 6b. Extras (large dirs the user opted in to) ----------
if [ -d "$EXTRACT_DIR/extras" ]; then
  step "Restoring extras from manifest"
  python3 - "$CFG_FILE" "$EXTRACT_DIR" <<'PY'
import json, os, sys, shutil, subprocess
cfg_file, extract_dir = sys.argv[1], sys.argv[2]
with open(cfg_file) as f:
    manifest = json.load(f)
for item in manifest.get("items", []):
    if item.get("type") != "extra":
        continue
    src = os.path.join(extract_dir, item["archivePath"])
    dst = item.get("source")
    if not dst or not os.path.exists(src):
        print(f"  skip: {item['archivePath']}")
        continue
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    print(f"  rsync -> {dst}")
    subprocess.run(["rsync", "-a", src + "/", dst + "/"], check=False)
PY
  green "  Extras restored"
fi

# ---------- 7. macOS defaults ----------
if [ -f "$EXTRACT_DIR/macos-defaults.json" ] && command -v /usr/bin/plutil >/dev/null; then
  step "Applying macOS defaults"
  python3 - "$EXTRACT_DIR/macos-defaults.json" <<'PY'
import json, subprocess, sys, os
with open(sys.argv[1]) as f:
    data = json.load(f)
for entry in data.get("defaults", []):
    domain = entry["domain"]
    key = entry["key"]
    typ = entry["type"]
    value = entry["value"]
    if typ == "string":
        value = os.path.expanduser(str(value))
    cmd = ["defaults", "write", domain, key, f"-{typ}", str(value).lower() if typ == "bool" else str(value)]
    print("  ", " ".join(cmd))
    subprocess.run(cmd, check=False)
PY
  killall Finder Dock SystemUIServer 2>/dev/null || true
  green "  macOS defaults applied"
fi

# ---------- 8. oh-my-zsh ----------
if [ ! -d "$HOME/.oh-my-zsh" ]; then
  step "Cloning oh-my-zsh (your .zshrc expects it)"
  git clone --depth=1 https://github.com/ohmyzsh/ohmyzsh.git "$HOME/.oh-my-zsh"
fi

# ---------- 9. Manual checklist ----------
cat <<EOF

$(green "==================================================")
$(green "Automated restore complete.")
$(green "==================================================")

Manual steps still required:

  1. SSH keys      -> copy id_ed25519* and known_hosts into ~/.ssh/
                      then: chmod 600 ~/.ssh/id_*; chmod 644 ~/.ssh/*.pub
  2. GitHub CLI    -> gh auth login
  3. AWS           -> aws sso login   (or paste ~/.aws/credentials)
  4. Docker        -> docker login    (re-auth to registries)
  5. VS Code Sync  -> Sign in via VS Code -> Settings -> Backup and Sync
  6. 1Password     -> Open app and sign in
  7. Browsers      -> Sign in to sync bookmarks/passwords
  8. Time Machine  -> Configure for ongoing local backups

Reference list of what was restored:
  cat $LOG_FILE

Manifest (what's mapped where):
  cat $CFG_FILE | jq .

EOF
